Repository AxaGuilDEv/Skizzle, pull requests merged in 2020-05, with the labels that each got.

#1 Worflow: add stale action
  .github/workflows/stale.yml
Labels: enhancement

#17 Update README.md
  README.md
Labels: documentation

#13 fix(Login): Logo for dark context
  public/assets/logo-skizzle-dark-context.svg
  src/layouts/Login/Login.scss
  src/layouts/Login/Login.svelte
Labels: bug

#19 chore(Configuration): Set up linter, prettier and package version
  .eslintrc
  .prettierrc
  CONTRIBUTING.md
  package.json
Labels: documentation

#14 fix(macOS): Tray icon for macOS
  public/assets/icon-macos@3x.png
  public/electron.js
Labels: bug

#27 Update README.md
  README.md
Labels: documentation

#23 Pull request status
  src/components/Pullrequest/Pullrequest.scss
  src/components/Pullrequest/Pullrequest.svelte
Labels: enhancement
