Repository AxaGuilDEv/Skizzle, pull requests merged in 2020-07, with the labels that each got.

#56 fix(Requester): Error 203
  src/components/MainView/MainView.scss
  src/components/MainView/MainView.svelte
  src/shared/requester.js
  src/shared/store.js
Labels: bug

#57 feat(Landing): New design
  docs/illustration.svg
  docs/index.html
  docs/logo-skizzle-dark-context.svg
  docs/styles.css
  docs/ui.jpg
Labels: enhancement

#58 fix(sign): remove macos signature
  .github/workflows/build.yml
  package.json
Labels: enhancement

#62 refactor(public): remove unused variables
  package.json
  public/splashscreen.html
Labels: fix
