Repository AxaGuilDEv/Skizzle, pull requests merged in 2020-06, with the labels that each got.

#22 fix(Shared): Display scrollbar
  public/global.css
Labels: bug

#28 fix(Login): White screen
  public/electron.js
  public/global.css
  src/components/App/App.scss
  src/components/Profile/Profile.scss
  src/layouts/Login/Login.scss
  src/layouts/Login/Login.svelte
Labels: bug

#25 Create release.yml
  .github/workflows/release.yml
Labels: enhancement, patch

#30 fix(Organizations): Handle error on projects fetch
  src/components/Settings/Settings.scss
  src/components/Settings/SettingsOrganizations.svelte
  src/shared/requester.js
Labels: bug, minor

#40 fix(List): Manual refresh on empty list
  src/components/MainView/MainView.scss
  src/components/MainView/MainView.svelte
Labels: bug, minor

#39 fix(Auth): Logout modal closing
  public/electron.js
  src/components/Settings/Settings.svelte
Labels: bug, minor

#43 change header bar for adapt it with the current environnement
  .github/workflows/build.yml
  public/global.css
  src/components/Header/Header.scss
  src/components/Header/Header.svelte
  src/components/Header/MacosBar.scss
  src/components/Header/MacosBar.svelte
  src/components/Header/WindowsBar.scss
  src/components/Header/WindowsBar.svelte
  src/components/MainView/MainView.scss
  src/components/MainView/MainView.svelte
  src/components/Profile/Profile.scss
  src/components/Settings/Settings.scss
  src/components/Tag/Tag.scss
Labels: enhancement

#50 fix(build): build for windows and macos on tag
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: bug

#51 feat(updater): add splashscreen with update info
  .github/workflows/test.yml
  .prettierrc
  CONTRIBUTING.md
  commitlint.config.js
  package.json
  public/electron.js
  public/global.css
  public/splashscreen.html
  public/updater.js
  pull_request_template.md
  src/components/MainView/MainView.scss
Labels: enhancement

#52 fix(Requester): fix the cloned PR and fake notifications
  src/shared/requester.js
Labels: bug

#53 fix(Login): Redirect to login if expired token
  public/electron.js
  src/shared/requester.js
Labels: bug

#3 fix(shared): remove unneeded defensive code
  src/shared/store.js
Labels: bug
