Repository AxaGuilDEv/Skizzle, pull requests merged in 2021-09, with the labels that each got.

#123 fix(customList): fixing title on custom list tab and more
  package-lock.json
  src/App.svelte
  src/components/CustomListSettings/CustomListSettings.svelte
Labels: svelte, component

#124 fix(site): fix download url
  docs/index.html
  docs/styles.css
Labels: bug

#125 Fix/intro
  package.json
  src/App.svelte
  src/views/Intro/Intro.svelte
Labels: bug, svelte, component

#126 fix(docs): release url
  docs/index.html
Labels: bug

#127 fix(docs): responsive
  docs/index.html
  docs/styles.css
Labels: bug
