Repository AxaGuilDEv/Skizzle, pull requests merged in 2022-01, with the labels that each got.

#143 Refactor/cleancode
  package.json
  src/components/CustomListSettings/CustomListSettings.svelte
  src/components/ImportExport/ImportExport.svelte
  src/components/Main/Main.svelte
  src/components/MultiSelector/MultiSelector.svelte
  src/components/Settings/Settings.svelte
  src/shared/stores/default.store.ts
  src/shared/utils.ts
Labels: bug, enhancement, dependencies, svelte, component, typescript

#144 feat(docs): add github call api for get the latest release of skizzle
  docs/index.html
  package-lock.json
  package.json
Labels: dependencies

#145 fix: handle old custom lists format
  package.json
  src/shared/stores/store.ts
Labels: bug, dependencies, typescript
